long = 0
arrBeam[0] = 0
dir = 0
dirPrev = 360
longCurrent = 0
longPrev = -1
rotate = true
switchRotate = true
switchZero = true
arrPos = [0,0]
frame = 0
frameTimer = 0
frameTimerMax = 5
maxFrame = (image_number - 1)
image_blend = c_aqua